#Data
num_points: ${datamodule.num_points}
transform: False
#Model
_target_: src.models.pointnet2_msg_retrieval.PointNet2RetrievalMSG
use_xyz: True
margin: 0.6
symmetric: False

# Retrieval training
encoder: pointnet2_msg
feat_dim: 512
lambda_deform_triplet: 0
deform_margin: 0.1

# Augmentation
aug_sketch: False
aug_shape: False
# Retrieval validation
val_deform: Falsef

# Keypoint Deformer
steps_KP: 100
num_structure_points: 16
KP_dist: Chamfer_dist
deformer_ckpt: logs/experiments/deformer_cage_sh2sh_template/checkpoints/last.ckpt
lambda_deform_sketch: 0
use_sketch_deformer: False
sketch_deformer_ckpt: logs/experiments/deformer_cage_sk2sh_template/checkpoints/last.ckpt
deform_sketch_loss: deform_sketch_loss_v1
deform_sketch_margin: 0.3

## Cage-based
# n_fps
cage_size: 1.4
ico_sphere_div: 1
n_influence_ratio: 1.0
lambda_init_points: 2.0
lambda_chamfer: 1.0
lambda_influence_predict_l2: 1e6

# Optimization
optimizer: sgd
weight_decay: 0.0
lr: 1e-2
schedular: step
lr_decay: 0.7
bn_momentum: 0.5
bnm_decay: 0.5
decay_step: 2e4
batch_size: ${datamodule.batch_size}
step_size: 20
gamma: 0.7
stage2_deform_only: False

#loss
tl_loss: True
lambda_KP_dist: 1.0
lambda_sym: 0.0

## Fitting loss type
loss_type: regression
regression_triplet_loss: regression_triplet_loss_v7
regression_loss: L1
neg_ratio: 1.
sigma_lr: 0.1
fixed_sigma: True
softmax_weight: 10
L2_norm: True
val_metric: acc@1
margin_max: 4
top2_max: null
learn_margin: False
margin_range: 0.9
fitting_gap: d1
#MISC
work_dir: ${work_dir}
#Visualize
vis: False
save_dir: ${work_dir}

# Multi fold
fold_id: ${datamodule.fold_id}
sketch_dir: ${datamodule.sketch_dir}
test_ckpt: best
test_data: ${datamodule.test_data}

# Multi category
category: ${datamodule.category}
