_target_: src.datamodules.SketchyVR_datamodule.SketchyVRDataModule
batch_size: 10
data_dir: /vol/vssp/datasets/multiview/3VS/datasets/FineGrained_3DSketch
mesh_dir: /vol/vssp/datasets/multiview/3VS/datasets/ShapeNet/shapenet
split_file: /vol/research/sketching/projects/VR_Sketch_lightning/project/data/shapenet_split/all.csv
category: '03001627'
dataset_loader: Shapes
test_dataset_loader: Shapes
train_list: list/hs/train.txt
train_shape_list: list/hs/train.txt
val_list: list/hs/val.txt
val_shape_list: list/hs/val.txt
test_list: list/hs/test.txt
test_shape_list: list/hs/test_shape.txt
source_type: sketch
target_type: shape
num_points: 1024
num_workers: 4
pin_memory: False
origin_val: True
sketch_dir: aligned_sketch
fold_id: 1
test_data: aligned_sketch
abstraction: 0.25