# trainer args for debugging model
_target_: pytorch_lightning.Trainer
gpus: -1  # set -1 to train on all GPUs abailable, set 0 to train on CPU only
# auto_select_gpus: True
max_epochs: 3
check_val_every_n_epoch: 1
gradient_clip_val: 0.5
# fast_dev_run: True  
limit_train_batches: 0.1
limit_val_batches: 0.1
limit_test_batches: 0.1
#val_check_interval: 1.0
# profiler: "simple"  # use profiler to print execution time profiling after training ends
# terminate_on_nan: true
progress_bar_refresh_rate: 10
# weights_summary: "full"
default_root_dir: "lightning_logs/"
# accumulate_grad_batches: 2