_target_: pytorch_lightning.Trainer
gpus: -1  # set -1 to train on all GPUs available, set 0 to train on CPU only
max_epochs: 500
min_epochs: 300
check_val_every_n_epoch: 5
gradient_clip_val: 0.05
num_sanity_val_steps: 1
progress_bar_refresh_rate: 10
weights_summary: null  # null in yaml represents python None value
default_root_dir: "lightning_logs/"
