_target_: pytorch_lightning.Trainer
gpus: -1  # set -1 to train on all GPUs available, set 0 to train on CPU only
min_steps: 2000
max_steps: 2000
log_every_n_steps: 10
val_check_interval: 100
num_sanity_val_steps: 1
progress_bar_refresh_rate: 10
weights_summary: null  # null in yaml represents python None value
default_root_dir: "lightning_logs/"
