model_checkpoint:
    _target_: src.callbacks.custom_callbacks.SelfModelCheckpoint
#    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val_loss"      # name of the logged metric which determines when model is improving
    save_top_k: 1           # save k best models (determined by above metric)
    save_last: True         # additionaly always save model from last epoch
    mode: "min"             # can be "max" or "min"
    every_n_train_steps: 100
    dirpath: checkpoints
    filename: "{val_loss:.3f}-{step}"
